// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "datacombo2.h"

/////////////////////////////////////////////////////////////////////////////
// CDatacombo2

IMPLEMENT_DYNCREATE(CDatacombo2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDatacombo2 properties

/////////////////////////////////////////////////////////////////////////////
// CDatacombo2 operations
